### ISSUE TITLE
Do not output sections that begin with #!

### ISSUE THREAD

**Issue by uri** [rsc/script#6]
It would be nice to ignore shebang comments. Some of my scripts look like:

```
#!/usr/bin/env sake

echo hello
```

So I can run it like `./my-script` (sake is my wrapper around this package).

Comments seem to be printed regardless of the `Quiet` setting.

**Comment by rsc** [comment]
If your 'sake' program is reading this file, then it seems like it could remove the #! itself, rather than defining that into the script package.
